
# site settings
title: Manoj Nathwani
email: '&#9608;&#9608;&#9608;&#9608;&#9608;&#9608;&#9608;&#9608;'
mailto: 'me@manoj.com'

# my settings
timezone: Europe/London
permalink: /articles/:year/:month/:day/:title
array: []

# Build settings
markdown: kramdown
gems:
  - jekyll-redirect-from
